### ISSUE TITLE
Automating test scripts

### ISSUE THREAD

**Issue by spr13** [HPCE/hpce-2016-cw4#11]
For the first part, I tried writing a shell script to automate the first tests but I was not able to output the sustained bandwidth (bytes/sec given by the command pv in the terminal) into a file. Since there are only 5 tests for the first plot, I guess I can do it manually but it would still be interesting to know how to do it. 

For the second part, I am a bit confused to how I am suppose to change the values of nIn and nOut during my tests.
The only test that is shown is:
```
cat w/random1024.bin | \
   bin/run_network w/n512_00.bin:simple \
   > w/random1024_simple.out
```
If I understand correctly 512 is nIn and 1024 is nOut. Please let me know if this is indeed the case.

**Comment by m8pple** [comment]
Getting values out of pv is a bit difficult as it uses console control
codes to keep updating in the same place. However, you can use the principle that

     time = data / bandwidth + startup-code

So try to choose a large enough amount of data that time is significantly
larger than the startup cost, then reverse the equation.

In order to vary nIn and nOut you'll need to vary the network.

For example, if you did something like (not tested, just free-typing):

    N="4 8 16 32";
    for i in N; do
        for j in N; do
          bin/generate_sparse_layer ${i} ${j} > w/layer_${i}_${j}.bin
        done
    done

then you'd end up with many different layers with different input and
output sizes.

**Comment by spr13** [comment]
Thank you I ran the tests on my VM and it seems to do reasonably well.
